### ISSUE TITLE
Reset malmo world when agent dies

### ISSUE THREAD

**Issue by lilphunky** [mickychetta/speed-miners#18]
Currently, the malmo world is only reset when the 30 second episode timer is up

**Comment by erichsueh3** [comment]
Will look similar to:
```
if episode_step >= MAX_EPISODE_STEPS or \
(obs[0, int(OBS_SIZE/2)-1, int(OBS_SIZE/2)] == 1 and \
obs[1, int(OBS_SIZE/2)-1, int(OBS_SIZE/2)] == 0 and \
command == 'move 1'):
    done = True
```

Where the second/third/fourth conditionals mean that the agent will move into a block of lava with the next move.
