### ISSUE TITLE
Add rails to observation space and add behavior to mine twice if rail is collected

### ISSUE THREAD

**Issue by erichsueh3** [mickychetta/speed-miners#28]

**Comment by erichsueh3** [comment]
Is this something we should even implement or is this more so on the agent's end to learn this behavior?

**Comment by mickychetta** [comment]
I don't want to add extra complexity to the project. Rails was intended for design and simulation purpose, not additional reward tuning and observation spaces. I don't think we should focus on it, what do you think?

**Comment by erichsueh3** [comment]
Yeah I agree, better to not focus on it from our side and let the agent learn on its own.
