### ISSUE TITLE
Remove cobwebs from XML

### ISSUE THREAD

**Issue by erichsueh3** [mickychetta/speed-miners#29]
Currently, cobwebs can be problematic when placed near lava. For example, if an agent does a `jumpmove` command onto the top of a cobweb that is over lava, the agent will not be able to escape the cobweb (this is true whenever the agent gets stuck in one). Eventually, the agent will sink close enough to the block to be considered touching it, but our manual check of touching lava doesn't work anymore ([see here](https://github.com/mickychetta/speed-miners/blob/main/agent.py#L160-L163)). We can either remove the cobwebs or figure out another way to signal the end of a mission. I was trying to figure out how `IsAlive` works before implementing a death check this way but I couldn't figure it out; maybe it could help here.

**Comment by mickychetta** [comment]
I'll remove the cobwebs
