### ISSUE TITLE
Add negative reward to bedrock

### ISSUE THREAD

**Issue by lilphunky** [mickychetta/speed-miners#8]
Bedrock is used for the grid boundaries (the walls) and for the layers underneath the mine. Would be best to add negative reward so the agent avoids mining these areas.

**Comment by erichsueh3** [comment]
Quick note: bedrock is mined due to the angle of the agent view currently (#16) so fixing that should fix the issue with bedrock being mined. Also, we will still add a negative reward for TOUCHING bedrock, as this indicates the agent has fallen into a hole.

**Comment by erichsueh3** [comment]
Also another note is that we have changed the grid boundaries from bedrock to stone so the agent is not penalized for touching the grid edges.
